version: '3'
services:
  api:
    container_name: blogo
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:8000
    env_file: ".env"
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
  postgres:
    container_name: blogo-db
    ports:
      - ${DB_PORT}:5432
    image: postgres:latest
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
